name: aspenroseboutique
favicon: null
layout_spectrum: 1
typography_spectrum: 0.54822
title: "Women's Clothing Boutique"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#afaca3'
    - '#d6d6d6'
    - '#a16967'
    - '#113c71'
  brandStrength: 0.1875
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
